version: '3.8'
services:
  # =========================================================
  # SERVIÇO DO BANCO DE DADOS (POSTGRESQL) 
  # =========================================================
  postgres:
    image: postgres:15-alpine
    container_name: postgres_app
    env_file:
      - .env
    ports:
      - "5432:5432"
    # Configura os discos virtuais e scripts automáticos
    volumes:
      # Garante que os dados salvos nas tabelas não sumam quando o container desligar
      - postgres_data:/var/lib/postgresql/data
      # Executa o script SQL de tabelas automaticamente na primeira vez que o banco subir
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
      
    # Testará de tempos em tempos se o banco realmente já ligou
    healthcheck:
      # O comando 'pg_isready' pega o usuário e banco direto da memória secreta do container (O $$ evita conflitos)
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s   # Faz o teste a cada 5 segundos
      timeout: 5s    # Tempo limite para o teste responder
      retries: 10    # Tenta até 10 vezes antes de marcar o container como quebrado

  # =========================================================
  # SERVIÇO DO SISTEMA EM PYTHON (APP)
  # =========================================================
  app:
    # Puxa a imagem encapsulada e independente gerada pelo GitHub Actions 
    #(Foco em Deploy Externo)
    image: ghcr.io/remalves/trabalho_3_gcsw:latest
    container_name: sistema_vendas  
    env_file:
      - .env
    # Regra de dependência: O Python só liga DEPOIS que o Postgres passar no teste do healthcheck
    depends_on:
      postgres:
        condition: service_healthy
    # Abre o canal de digitação padrão (input) e aloca um terminal virtual interativo
    stdin_open: true 
    tty: true        
    command: ["python", "-u", "main.py"]
    networks:
      - app-network

  # =========================================================
  # 3. GERENCIADOR VISUAL DO BANCO (ADMINER)
  # =========================================================
  adminer:
    # Baixa a ferramenta visual Adminer (Acessível pelo navegador em http://localhost:8080)
    image: adminer
    container_name: adminer_app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
volumes:
  postgres_data: